@extends('layouts.portal')
@section('title','Reviewer dashboard') @section('section','Peer review') @section('eyebrow','Independent assessment') @section('page-title','Review assignments')
@section('page-description','Read assigned manuscripts, record structured feedback, and submit a final recommendation. Manuscript content remains immutable.')
@section('content')
<div class="metric-grid"><x-portal.metric label="Invitations" :value="$stats['assigned']" tone="gold"/><x-portal.metric label="Accepted / pending" :value="$stats['in_progress']" tone="blue"/><x-portal.metric label="Completed" :value="$stats['completed']"/><x-portal.metric label="All assignments" :value="$stats['total']"/><x-portal.metric label="Overdue" :value="$stats['overdue']" tone="gold"/></div>
<div class="portal-card"><div class="portal-card-head"><div><h2>Your assignments</h2><p>Prioritised by due date; completed reports remain available as read-only history.</p></div></div>
<form class="filter-bar" method="get" action="{{ route('reviewer.dashboard') }}">
<div class="portal-field"><label for="q">Search manuscripts</label><input class="portal-input" id="q" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Title, keyword, or manuscript ID"></div>
<div class="portal-field"><label for="status">Assignment status</label><select class="portal-select" id="status" name="status"><option value="">All assignments</option>@foreach(['assigned'=>'Invitations','in_progress'=>'In progress','completed'=>'Completed reports','overdue'=>'Overdue','declined'=>'Declined','cancelled'=>'Cancelled'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '')===$value)>{{ $label }}</option>@endforeach</select></div>
<button class="portal-button primary" type="submit">Apply filters</button><a class="portal-button" href="{{ route('reviewer.dashboard') }}">Reset</a></form>
@if($reviews->isEmpty())<x-portal.empty title="No matching assignments" message="Try another filter. Invitations appear when an editor assigns a manuscript to your reviewer account. Accept an invitation to unlock manuscript downloads and the review form." />@else<div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Manuscript</th><th>Round</th><th>Status</th><th>Due</th><th>Recommendation</th><th></th></tr></thead><tbody>@foreach($reviews as $review)<tr><td><a class="row-title" href="{{ route('reviewer.reviews.show',$review) }}">{{ $review->article->title }}</a><small>{{ $review->article->workflow?->manuscript_id }} · Assigned {{ $review->created_at->format('d M Y') }}{{ $review->article->trashed() ? ' · Archived manuscript' : '' }}</small></td><td>{{ $review->submission?->round ?? '—' }}</td><td><x-portal.status :value="$review->status" /></td><td>@if($review->due_at)<span @if(in_array($review->status->value, ['assigned','in_progress']) && $review->due_at->isPast()) style="color:var(--portal-danger);font-weight:700" @endif>{{ $review->due_at->format('d M Y') }}</span>@else No deadline @endif</td><td>{{ $review->recommendation ? str($review->recommendation->value)->replace('_',' ')->headline() : '—' }}</td><td><a class="portal-button small" href="{{ route('reviewer.reviews.show',$review) }}">{{ match($review->status->value) { 'assigned' => 'Respond to invitation', 'in_progress' => 'Continue review', 'completed' => 'View report', default => 'View details' } }}</a></td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $reviews->links() }}</div>@endif</div>
<div class="portal-card"><div class="portal-card-head"><h2>Review workflow</h2></div><div class="portal-card-body"><p><strong>1. Respond to an invitation.</strong> Check the abstract, deadline, and conflicts of interest, then accept or decline.</p><p><strong>2. Assess the manuscript.</strong> Accepted assignments provide the manuscript, available supporting files, and a structured report with comments to the author, confidential notes, and an optional attachment.</p><p><strong>3. Submit your recommendation.</strong> Completed reports remain available in your history and are locked after submission. Contact the editorial team if a correction is needed.</p></div></div>
@endsection
