@php $editing=isset($article); $details=old('author_details',$editing?$article->authors->map(fn($a)=>$a->only(['name','email','organization','department','country','orcid']))->all():[['name'=>auth()->user()->name,'email'=>auth()->user()->email,'organization'=>auth()->user()->organization]]);$details=$details?:[['name'=>auth()->user()->name,'email'=>auth()->user()->email]]; @endphp
<form method="post" class="portal-form" enctype="multipart/form-data" action="{{ $editing?route('author.articles.update',$article):route('author.articles.store') }}" data-manuscript-wizard @if($editing) data-autosave="{{ route('author.articles.autosave',$article) }}" @endif>@csrf @if($editing)@method('put')<input type="hidden" name="updated_at" value="{{ $article->updated_at->toISOString() }}">@endif
@if($editing)<p class="portal-help" data-autosave-status role="status" aria-live="polite">Article details autosave. Use Save draft for authors and files; confirm declarations when submitting.</p>@endif
<nav class="workflow-tabs" aria-label="Submission steps">@foreach(['Article details','Authors','Files','Declarations','Review & submit'] as $i=>$label)<button type="button" class="portal-button" data-wizard-goto="{{ $i }}">{{ $i+1 }}. {{ $label }}</button>@endforeach</nav>
<section class="portal-card" data-wizard-step><div class="portal-card-head"><h2>1. Article details</h2></div><div class="portal-card-body portal-form">
<label>Article title<input class="portal-input" name="title" value="{{ old('title',$article->title??'') }}" maxlength="240" required></label>
<label>Article type<select class="portal-select" name="publication_type">@foreach(['article','research','review','essay','case-study','editorial'] as $type)<option value="{{ $type }}" @selected(old('publication_type',$article->publication_type??'article')===$type)>{{ str($type)->headline() }}</option>@endforeach</select></label>
<label>Abstract<textarea class="portal-textarea" name="abstract" rows="7">{{ old('abstract',$article->abstract??'') }}</textarea></label>
<label>Keywords (comma separated)<input class="portal-input" name="keywords" value="{{ is_array(old('keywords'))?implode(', ',old('keywords')):old('keywords',implode(', ',$article->keywords??[])) }}"></label>
<label>Category<select class="portal-select" name="category_id"><option value="">Select discipline</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$article->category_id??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
<label>References (one per line)<textarea class="portal-textarea" name="references" rows="5">{{ is_array(old('references'))?implode("\n",old('references')):old('references',implode("\n",$article->references??[])) }}</textarea></label>
<x-portal.rich-editor name="content" id="content" :value="old('content',$article->content??'')" />
</div></section>
<section class="portal-card" data-wizard-step><div class="portal-card-head"><h2>2. Authors and affiliations</h2></div><div class="portal-card-body portal-form"><div data-author-list>@foreach($details as $index=>$detail)<fieldset class="portal-form" data-author-row><legend>Author {{ $index+1 }}</legend>@foreach(['name'=>'Name','email'=>'Email','organization'=>'Institution','department'=>'Department','country'=>'Country','orcid'=>'ORCID'] as $key=>$label)<label>{{ $label }}<input class="portal-input" name="author_details[{{ $index }}][{{ $key }}]" value="{{ $detail[$key]??'' }}" type="{{ $key==='email'?'email':'text' }}" @required(in_array($key,['name','email','organization']))></label>@endforeach<label class="check-row"><input type="radio" name="corresponding_index" value="{{ $index }}" @checked(old('corresponding_index',$editing?$article->authors->search(fn($a)=>$a->pivot->is_corresponding):0)==$index)>Corresponding author</label><button class="portal-button small" type="button" data-remove-author>Remove author</button></fieldset>@endforeach</div><button class="portal-button" type="button" data-add-author>Add co-author</button></div></section>
<section class="portal-card" data-wizard-step><div class="portal-card-head"><h2>3. Manuscript files</h2></div><div class="portal-card-body portal-form"><p>Private PDF, DOC or DOCX, up to 20 MB per file and 32 MB total per request. Previous uploads are retained.</p>@foreach(['manuscript'=>'Manuscript','cover_letter'=>'Cover letter','supplementary'=>'Supplementary files (up to 10)','response'=>'Response to reviewers (revisions)'] as $key=>$label)<label>{{ $label }}<input class="portal-input" type="file" name="{{ $key }}{{ $key==='supplementary'?'[]':'' }}" @if($key==='supplementary') multiple @endif accept="{{ $key==='supplementary'?'.pdf,.doc,.docx,.jpg,.jpeg,.png,.webp,.svg':'.pdf,.doc,.docx' }}"></label>@endforeach</div></section>
<section class="portal-card" data-wizard-step><div class="portal-card-head"><h2>4. Declarations</h2></div><div class="portal-card-body portal-form">@foreach(['original'=>'The manuscript is original','exclusive'=>'Not submitted elsewhere','authors_approve'=>'All authors approve submission','ethics'=>'Ethics declaration accepted','conflicts'=>'Conflicts of interest declared'] as $key=>$label)<label class="check-row"><input type="checkbox" name="declarations[{{ $key }}]" value="1" @checked(old('declarations.'.$key))>{{ $label }}</label>@endforeach</div></section>
<section class="portal-card" data-wizard-step><div class="portal-card-head"><h2>5. Review and submit</h2></div><div class="portal-card-body portal-form"><div data-submission-summary></div><p>Submission locks the manuscript for editorial review. A permanent manuscript ID is assigned on first submission.</p><label>Submission / revision notes<textarea class="portal-textarea" name="comments">{{ old('comments') }}</textarea></label><button class="portal-button primary" name="intent" value="submit">Submit manuscript</button></div></section>
<div class="form-actions"><button type="button" class="portal-button" data-wizard-prev>Previous</button><button type="button" class="portal-button" data-wizard-next>Next</button><button class="portal-button" name="intent" value="draft" formnovalidate>Save draft</button></div></form>
