@php $editing = isset($article); $selectedTags = old('tags', $editing ? $article->tags->pluck('id')->all() : []); $ownerAuthor=auth()->user()->author()->first(); $selectedCoAuthors=old('co_authors',$editing?$article->authors->where('id','!=',$ownerAuthor?->id)->pluck('id')->all():[]); @endphp
<form class="portal-form" method="post" action="{{ $editing ? route('author.articles.update',$article) : route('author.articles.store') }}" enctype="multipart/form-data" @if($editing) data-autosave="{{ route('author.articles.autosave',$article) }}" @endif data-loading>@csrf @if($editing)@method('put')<input type="hidden" name="updated_at" value="{{ $article->updated_at->toISOString() }}">@endif
<div class="dashboard-grid" style="align-items:start"><div class="portal-card"><div class="portal-card-head"><div><h2>Manuscript</h2><p>Clear, descriptive language helps editors and readers.</p></div></div><div class="portal-card-body portal-form">
    <div class="portal-field"><label for="title">Title</label><input class="portal-input" id="title" name="title" value="{{ old('title',$article->title ?? '') }}" required maxlength="240"><x-portal.field-error name="title" /></div>
    <div class="portal-field"><label for="subtitle">Subtitle <span>optional</span></label><input class="portal-input" id="subtitle" name="subtitle" value="{{ old('subtitle',$article->subtitle ?? '') }}" maxlength="300"><x-portal.field-error name="subtitle" /></div>
    <div class="portal-field"><label for="abstract">Abstract</label><textarea class="portal-textarea" id="abstract" name="abstract" rows="7">{{ old('abstract',$article->abstract ?? '') }}</textarea><p class="portal-help">Summarise the question, approach, and central finding.</p><x-portal.field-error name="abstract" /></div>
    <x-portal.rich-editor name="content" id="content" :value="old('content',$article->content ?? '')" />
    <div class="portal-field"><label for="references">References <span>one reference per line</span></label><textarea class="portal-textarea" id="references" name="references" rows="8">{{ old('references',implode("\n",$article->references ?? [])) }}</textarea><x-portal.field-error name="references" /></div>
</div></div>
<div class="portal-form"><div class="portal-card"><div class="portal-card-head"><h2>Classification</h2></div><div class="portal-card-body portal-form">
    <div class="portal-field"><label for="category_id">Category</label><select class="portal-select" id="category_id" name="category_id"><option value="">Choose a discipline</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id',$article->category_id ?? '')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select><x-portal.field-error name="category_id" /></div>
    <div class="portal-field"><label for="publication_type">Publication type</label><select class="portal-select" id="publication_type" name="publication_type" required>@foreach(['article'=>'Article','research'=>'Research paper','review'=>'Literature review','essay'=>'Essay','case-study'=>'Case study','editorial'=>'Editorial'] as $value=>$label)<option value="{{ $value }}" @selected(old('publication_type',$article->publication_type ?? 'article')===$value)>{{ $label }}</option>@endforeach</select></div>
    <fieldset class="portal-field"><legend>Topics / tags</legend><div class="choice-grid">@foreach($tags as $tag)<label class="choice-card"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked(in_array($tag->id,$selectedTags))> {{ $tag->name }}</label>@endforeach</div><x-portal.field-error name="tags" /></fieldset>
    <fieldset class="portal-field"><legend>Co-authors <span>optional</span></legend><p class="portal-help">You remain the corresponding first author. Select only collaborators who contributed to this work.</p><div style="max-height:220px;overflow:auto">@foreach($coAuthors as $coAuthor)<label class="check-row" style="margin:.55rem 0"><input type="checkbox" name="co_authors[]" value="{{ $coAuthor->id }}" @checked(in_array($coAuthor->id,$selectedCoAuthors))><span>{{ $coAuthor->name }} <small>{{ $coAuthor->organization }}</small></span></label>@endforeach</div><x-portal.field-error name="co_authors" /></fieldset>
    <div class="portal-field"><label for="keywords">Keywords <span>comma separated</span></label><input class="portal-input" id="keywords" name="keywords" value="{{ old('keywords',implode(', ', $article->keywords ?? [])) }}"><x-portal.field-error name="keywords" /></div>
</div></div>
<div class="portal-card"><div class="portal-card-head"><h2>Files &amp; details</h2></div><div class="portal-card-body portal-form">
    <div class="portal-field"><label for="featured_image">Featured image <span>JPG, PNG, WebP · 8 MB</span></label><input class="portal-input" id="featured_image" type="file" name="featured_image" accept="image/jpeg,image/png,image/webp"><x-portal.field-error name="featured_image" /></div>
    <div class="portal-field"><label for="manuscript_pdf">Manuscript PDF <span>private · 20 MB</span></label><input class="portal-input" id="manuscript_pdf" type="file" name="manuscript_pdf" accept="application/pdf"><x-portal.field-error name="manuscript_pdf" /></div>
    <div class="portal-field"><label for="supporting_documents">Supporting documents <span>up to 6 private PDF/Word files</span></label><input class="portal-input" id="supporting_documents" type="file" name="supporting_documents[]" multiple accept=".pdf,.doc,.docx"><x-portal.field-error name="supporting_documents" /></div>
    <div class="portal-field"><label for="doi">DOI <span>if already assigned</span></label><input class="portal-input" id="doi" name="doi" value="{{ old('doi',$article->doi ?? '') }}"></div>
    <div class="portal-field"><label for="excerpt">Reader excerpt</label><textarea class="portal-textarea" id="excerpt" name="excerpt" rows="4">{{ old('excerpt',$article->excerpt ?? '') }}</textarea></div>
    @if($editing)<div class="portal-field"><label for="change_summary">Version note</label><textarea class="portal-textarea" id="change_summary" name="change_summary" rows="3" placeholder="What changed in this revision?">{{ old('change_summary') }}</textarea></div>@endif
</div></div></div></div>
<div class="form-actions">@if($editing)<span class="autosave-status" data-autosave-status>All changes saved</span>@endif<a class="portal-button" href="{{ $editing ? route('author.articles.show',$article) : route('author.articles.index') }}">Cancel</a><button class="portal-button primary" type="submit" data-loading-text="Saving…">{{ $editing ? 'Save version' : 'Create draft' }}</button></div>
</form>
