@extends('layouts.portal')
@section('title', 'My manuscripts') @section('section', 'Author studio') @section('eyebrow', 'Your archive') @section('page-title', 'My manuscripts')
@section('page-description', 'Search, filter, and follow each submission through the editorial process.')
@section('page-actions')<a class="portal-button primary" href="{{ route('author.articles.create') }}"><x-portal.icon name="plus" :size="17" />New manuscript</a>@endsection
@section('content')
<div class="portal-card"><form class="filter-bar" method="get"><div class="portal-field search-field"><label for="q">Search manuscripts</label><input class="portal-input" id="q" name="q" value="{{ request('q') }}" placeholder="Title, abstract, keyword…"></div><div class="portal-field"><label for="status">Status</label><select class="portal-select" id="status" name="status"><option value="">Every status</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div><button class="portal-button" type="submit"><x-portal.icon name="search" :size="17" />Filter</button>@if(request()->hasAny(['q','status']))<a class="portal-button" href="{{ route('author.articles.index') }}">Clear</a>@endif</form>
@if($articles->isEmpty())<x-portal.empty title="No manuscripts found" message="Adjust the filter or begin a new piece of work." action="New manuscript" :href="route('author.articles.create')" />@else
<div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Manuscript</th><th>Category</th><th>Status</th><th>Submitted</th><th>Updated</th><th>Feedback</th><th></th></tr></thead><tbody>@foreach($articles as $article)<tr><td><a class="row-title" href="{{ route('author.articles.show',$article) }}">{{ $article->title }}</a><small>{{ $article->publication_type }}</small></td><td>{{ $article->category?->name ?? '—' }}</td><td><x-portal.status :value="$article->status" /></td><td>{{ $article->submitted_at?->format('d M Y') ?? 'Not submitted' }}</td><td>{{ $article->updated_at->format('d M Y') }}</td><td>{{ $article->reviews->whereNotNull('completed_at')->count() ? $article->reviews->whereNotNull('completed_at')->count().' report(s)' : '—' }}</td><td><div class="row-actions"><a class="portal-button small" href="{{ route('author.articles.show',$article) }}">View</a>@if(in_array($article->status,[\App\Enums\ArticleStatus::Draft,\App\Enums\ArticleStatus::RevisionRequired,\App\Enums\ArticleStatus::Rejected],true))<a class="portal-button small" href="{{ route('author.articles.edit',$article) }}">Edit</a>@endif</div></td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $articles->links() }}</div>@endif</div>
@endsection
