@extends('layouts.portal')
@section('title',$article->title) @section('section','Author studio') @section('eyebrow','Manuscript record') @section('page-title',$article->title)
@section('page-description',$article->subtitle ?: 'Follow this manuscript’s versions, submissions, and editorial feedback.')
@section('page-actions')@if(in_array($article->status,[\App\Enums\ArticleStatus::Draft,\App\Enums\ArticleStatus::RevisionRequired,\App\Enums\ArticleStatus::Rejected],true))<div class="portal-card"><div class="portal-card-body"><a class="portal-button primary" href="{{ route('author.articles.edit',$article) }}">Complete files and declarations to submit</a></div></div>@endif @if($article->pdf_path)<a class="portal-button" href="{{ route('author.articles.manuscript',$article) }}"><x-portal.icon name="download" :size="17" />PDF</a>@endif @endsection
@section('content')<p><a class="portal-button primary" href="{{ route('workflow.show',$article) }}">Open manuscript workflow</a></p>
<div class="dashboard-grid" style="align-items:start"><div class="portal-form">
<div class="portal-card"><div class="portal-card-head"><div><h2>Manuscript overview</h2><p>Last updated {{ $article->updated_at->format('d M Y, H:i') }}</p></div><x-portal.status :value="$article->status" /></div><div class="portal-card-body"><dl class="detail-list"><div><dt>Category</dt><dd>{{ $article->category?->name ?? 'Not set' }}</dd></div><div><dt>Publication type</dt><dd>{{ str($article->publication_type)->headline() }}</dd></div><div><dt>Submitted</dt><dd>{{ $article->submitted_at?->format('d M Y, H:i') ?? 'Not submitted' }}</dd></div><div><dt>Reading time</dt><dd>{{ $article->reading_time_minutes }} minutes</dd></div><div><dt>Keywords</dt><dd>{{ implode(', ',$article->keywords ?? []) ?: '—' }}</dd></div><div><dt>Tags</dt><dd>{{ $article->tags->pluck('name')->join(', ') ?: '—' }}</dd></div></dl></div></div>
@php $reports=$article->submissions->flatMap->reviews->whereNotNull('completed_at'); @endphp
<div class="portal-card"><div class="portal-card-head"><div><h2>Reviewer feedback</h2><p>Comments shared with authors; confidential editorial notes are never shown here.</p></div></div><div class="portal-card-body">@forelse($reports as $review)<article style="padding:1rem 0;border-bottom:1px solid var(--portal-line)"><div style="display:flex;justify-content:space-between;gap:1rem"><strong>Review round {{ $review->submission?->round }}</strong><x-portal.status :value="$review->recommendation" /></div><p style="white-space:pre-wrap;line-height:1.65;font-size:.85rem">{{ $review->comments_to_author }}</p>@foreach($review->comments as $comment)<blockquote style="border-left:3px solid var(--portal-mint);margin:1rem 0;padding-left:1rem"><small>{{ $comment->location ?: 'General comment' }}</small><p>{{ $comment->body }}</p></blockquote>@endforeach</article>@empty<x-portal.empty title="No reviewer report yet" message="Feedback shared by completed reviewers will appear here." />@endforelse</div></div>
</div><aside class="portal-form">
<div class="portal-card"><div class="portal-card-head"><h2>Version history</h2></div><div class="portal-card-body"><div class="timeline">@forelse($article->versions as $version)<div class="timeline-item"><strong>Version {{ $version->version_number }}</strong><p>{{ $version->change_summary ?: 'Snapshot' }}</p><small>{{ $version->created_at->format('d M Y, H:i') }} · {{ $version->creator?->name ?? 'System' }}</small></div>@empty<p class="portal-help">The first snapshot is created when you save or submit.</p>@endforelse</div></div></div>
</aside></div>
@endsection
