@extends('layouts.portal')
@section('title',$article->title) @section('section','Author studio') @section('eyebrow','Manuscript record') @section('page-title',$article->title)
@section('page-description',$article->subtitle ?: 'Follow this manuscript’s versions, submissions, and editorial feedback.')
@section('page-actions')@if(in_array($article->status,[\App\Enums\ArticleStatus::Draft,\App\Enums\ArticleStatus::RevisionRequired,\App\Enums\ArticleStatus::Rejected],true))<a class="portal-button primary" href="{{ route('author.articles.edit',$article) }}">Edit manuscript</a>@endif @if($article->pdf_path)<a class="portal-button" href="{{ route('author.articles.manuscript',$article) }}"><x-portal.icon name="download" :size="17" />PDF</a>@endif @endsection
@section('content')
<div class="dashboard-grid" style="align-items:start"><div class="portal-form">
<div class="portal-card"><div class="portal-card-head"><div><h2>Manuscript overview</h2><p>Last updated {{ $article->updated_at->format('d M Y, H:i') }}</p></div><x-portal.status :value="$article->status" /></div><div class="portal-card-body"><dl class="detail-list"><div><dt>Category</dt><dd>{{ $article->category?->name ?? 'Not set' }}</dd></div><div><dt>Publication type</dt><dd>{{ str($article->publication_type)->headline() }}</dd></div><div><dt>Submitted</dt><dd>{{ $article->submitted_at?->format('d M Y, H:i') ?? 'Not submitted' }}</dd></div><div><dt>Reading time</dt><dd>{{ $article->reading_time_minutes }} minutes</dd></div><div><dt>Keywords</dt><dd>{{ implode(', ',$article->keywords ?? []) ?: '—' }}</dd></div><div><dt>Tags</dt><dd>{{ $article->tags->pluck('name')->join(', ') ?: '—' }}</dd></div></dl></div></div>
@php $reports=$article->submissions->flatMap->reviews->whereNotNull('completed_at'); @endphp
<div class="portal-card"><div class="portal-card-head"><div><h2>Reviewer feedback</h2><p>Comments shared with authors; confidential editorial notes are never shown here.</p></div></div><div class="portal-card-body">@forelse($reports as $review)<article style="padding:1rem 0;border-bottom:1px solid var(--portal-line)"><div style="display:flex;justify-content:space-between;gap:1rem"><strong>Review round {{ $review->submission?->round }}</strong><x-portal.status :value="$review->recommendation" /></div><p style="white-space:pre-wrap;line-height:1.65;font-size:.85rem">{{ $review->comments_to_author }}</p>@foreach($review->comments as $comment)<blockquote style="border-left:3px solid var(--portal-mint);margin:1rem 0;padding-left:1rem"><small>{{ $comment->location ?: 'General comment' }}</small><p>{{ $comment->body }}</p></blockquote>@endforeach</article>@empty<x-portal.empty title="No reviewer report yet" message="Feedback shared by completed reviewers will appear here." />@endforelse</div></div>
</div><aside class="portal-form">
@if(in_array($article->status,[\App\Enums\ArticleStatus::Draft,\App\Enums\ArticleStatus::RevisionRequired,\App\Enums\ArticleStatus::Rejected],true))<div class="portal-card"><div class="portal-card-head"><h2>{{ $article->status===\App\Enums\ArticleStatus::RevisionRequired ? 'Resubmit revision' : 'Submit for review' }}</h2></div><div class="portal-card-body portal-form"><p class="portal-help">Submission locks the manuscript while editors assess it. Confirm that author details, abstract, content, category, references, and files are final.</p><form class="portal-form" method="post" action="{{ route('author.articles.submit',$article) }}" data-confirm="Submit this manuscript to the editorial office?" data-loading>@csrf<div class="portal-field"><label for="cover_letter">Cover letter <span>optional</span></label><textarea class="portal-textarea" id="cover_letter" name="cover_letter" rows="5" placeholder="Context for the editors…"></textarea></div><div class="check-row"><input id="confirmation" name="confirmation" type="checkbox" value="1" required><label for="confirmation">I confirm this work is ready for editorial review and complies with research integrity requirements.</label></div><x-portal.field-error name="confirmation" /><button class="portal-button primary" type="submit" data-loading-text="Submitting…">{{ $article->status===\App\Enums\ArticleStatus::RevisionRequired ? 'Submit revised version' : 'Submit manuscript' }}</button></form></div></div>@endif
<div class="portal-card"><div class="portal-card-head"><h2>Version history</h2></div><div class="portal-card-body"><div class="timeline">@forelse($article->versions as $version)<div class="timeline-item"><strong>Version {{ $version->version_number }}</strong><p>{{ $version->change_summary ?: 'Snapshot' }}</p><small>{{ $version->created_at->format('d M Y, H:i') }} · {{ $version->creator?->name ?? 'System' }}</small></div>@empty<p class="portal-help">The first snapshot is created when you save or submit.</p>@endforelse</div></div></div>
@if(in_array($article->status,[\App\Enums\ArticleStatus::Draft,\App\Enums\ArticleStatus::Rejected],true))<form method="post" action="{{ route('author.articles.destroy',$article) }}" data-confirm="Archive this manuscript? This cannot be undone from your workspace.">@csrf @method('delete')<button class="portal-button danger" type="submit">Archive manuscript</button></form>@endif
</aside></div>
@endsection
