@extends('layouts.portal')
@section('title','Editorial dashboard') @section('section','Editorial command centre') @section('eyebrow','Publication pulse') @section('page-title','Today at octaleads Journal')
@section('page-description','A live view of submissions, publication output, audience activity, and operational work.')
@section('page-actions')<a class="portal-button" href="{{ route('admin.submissions.index') }}">Review queue</a><a class="portal-button primary" href="{{ route('admin.articles.create') }}"><x-portal.icon name="plus" :size="17" />New article</a>@endsection
@section('content')
<div class="metric-grid"><x-portal.metric label="Published" :value="$stats['published']" hint="Of {$stats['articles']} total"/><x-portal.metric label="Pending submissions" :value="$stats['pending']" tone="gold" hint="Awaiting a decision"/><x-portal.metric label="Authors" :value="$stats['authors']" tone="blue" hint="{$stats['users']} registered users"/><x-portal.metric label="Article views" :value="$stats['views']" hint="Recorded readership"/></div>
<div class="dashboard-grid"><div class="portal-card"><div class="portal-card-head"><div><h2>Publication cadence</h2><p>Articles published by month</p></div></div><div class="portal-card-body">@php $max=max(1,$monthlyPublications->max('value')??1); @endphp@if($monthlyPublications->isEmpty())<x-portal.empty title="No publication history yet" message="Monthly output will appear after the first article is published." />@else<div class="chart-bars" role="img" aria-label="Monthly publication bar chart">@foreach($monthlyPublications as $point)<div class="chart-bar" title="{{ $point['label'] }}: {{ $point['value'] }}"><strong style="font-size:.65rem">{{ $point['value'] }}</strong><i style="height:{{ max(3,($point['value']/$max)*145) }}px"></i><span>{{ $point['label'] }}</span></div>@endforeach</div>@endif</div></div>
<div class="portal-card"><div class="portal-card-head"><div><h2>Operational snapshot</h2><p>Content and audience</p></div></div><div class="portal-card-body"><dl class="detail-list"><div><dt>Drafts</dt><dd>{{ number_format($stats['drafts']) }}</dd></div><div><dt>Categories</dt><dd>{{ number_format($stats['categories']) }}</dd></div><div><dt>Tags</dt><dd>{{ number_format($stats['tags']) }}</dd></div><div><dt>New enquiries</dt><dd>{{ number_format($stats['contacts']) }}</dd></div><div><dt>Subscribers</dt><dd>{{ number_format($stats['subscribers']) }}</dd></div><div><dt>Users</dt><dd>{{ number_format($stats['users']) }}</dd></div></dl></div></div></div>
<div class="dashboard-grid" style="margin-top:1.25rem"><div class="portal-card"><div class="portal-card-head"><div><h2>Most read</h2><p>Published articles by recorded views</p></div><a class="portal-button small" href="{{ route('admin.articles.index',['status'=>'published']) }}">All published</a></div>@if($popularArticles->isEmpty())<x-portal.empty title="No readership data" message="Popular articles will appear as readers visit published work." />@else<div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Article</th><th>Category</th><th>Views</th></tr></thead><tbody>@foreach($popularArticles as $article)<tr><td><a class="row-title" href="{{ route('admin.articles.show',$article) }}">{{ $article->title }}</a></td><td>{{ $article->category?->name ?? '—' }}</td><td>{{ number_format($article->view_count) }}</td></tr>@endforeach</tbody></table></div>@endif</div>
<div class="portal-card"><div class="portal-card-head"><div><h2>Recent activity</h2><p>Security and editorial audit trail</p></div><a class="portal-button small" href="{{ route('admin.audit.index') }}">Audit log</a></div><div class="portal-card-body"><div class="timeline">@forelse($activity as $item)<div class="timeline-item"><strong>{{ str($item->event)->replace('_',' ')->headline() }}</strong><p>{{ $item->description ?: class_basename($item->auditable_type ?? 'Record').' changed' }}</p><small>{{ $item->actor?->name ?? 'System' }} · {{ $item->created_at->diffForHumans() }}</small></div>@empty<p class="portal-help">No activity recorded yet.</p>@endforelse</div></div></div></div>
@endsection
