@if(in_array($action,['submit','revise']))
<p>Review the article details, author list and files before submitting. All versions are retained.</p>
@foreach(['manuscript'=>'Manuscript','cover_letter'=>'Cover letter','supplementary'=>'Supplementary files (up to 10)','response'=>'Response to reviewers'] as $key=>$label)@if($key!=='response'||$action==='revise')<label>{{ $label }} (PDF / DOC / DOCX, 20 MB)<input class="portal-input" type="file" name="{{ $key }}{{ $key==='supplementary'?'[]':'' }}" @if($key==='supplementary') multiple @endif accept=".pdf,.doc,.docx" @required($action==='revise'&&in_array($key,['manuscript','response']))></label>@endif @endforeach
<fieldset><legend>Declarations</legend>@foreach(['original'=>'The manuscript is original','exclusive'=>'Not submitted elsewhere','authors_approve'=>'All authors approve submission','ethics'=>'Ethics declaration accepted','conflicts'=>'Conflicts of interest declared'] as $key=>$label)<label class="check-row"><input type="checkbox" name="declarations[{{ $key }}]" value="1" required>{{ $label }}</label>@endforeach</fieldset>
@endif
@if($action==='approve_check')<fieldset><legend>Initial check</legend>@foreach(['manuscript'=>'Manuscript uploaded','cover_letter'=>'Cover letter uploaded','authors'=>'Author details complete','abstract'=>'Abstract complete','keywords'=>'Keywords complete','references'=>'References available','documents'=>'Required documents present','format'=>'Format correct'] as $key=>$label)<label class="check-row"><input type="checkbox" name="checklist[{{ $key }}]" value="1" required>{{ $label }}</label>@endforeach</fieldset>@endif
@if($action==='save_similarity')<label>Assessment status<select class="portal-select" name="similarity_status">@foreach(['pending','passed','needs_clarification','failed'] as $s)<option value="{{ $s }}">{{ str($s)->headline() }}</option>@endforeach</select></label>@endif
@if(in_array($action,['pass_similarity','save_similarity']))<label>Similarity percentage<input class="portal-input" name="similarity" type="number" min="0" max="100" step="0.01" required></label><label>Similarity report PDF<input class="portal-input" type="file" name="report" accept=".pdf" required></label>@endif
@if($action==='assign_reviewer')<label>Reviewer<select class="portal-select" name="reviewer_id" required><option value="">Select reviewer</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->id }}" @disabled(!data_get($reviewer->reviewer_profile,'available',true))>{{ $reviewer->name }} · {{ $reviewer->organization }} · {{ data_get($reviewer->reviewer_profile,'expertise') }} · {{ $reviewer->active_reviews_count }} active / {{ $reviewer->completed_reviews_count }} completed</option>@endforeach</select></label><label>Invitation response deadline<input class="portal-input" name="invitation_deadline" type="date" value="{{ now()->addDays(config('workflow.deadlines.invitation'))->format('Y-m-d') }}" required></label><label>Editor message<textarea class="portal-textarea" name="editor_message" required></textarea></label>@endif
@if(in_array($action,['minor_revision','major_revision','assign_reviewer','send_proof']))<label>Deadline<input class="portal-input" type="date" name="deadline" value="{{ now()->addDays(config('workflow.deadlines.'.match($action){'minor_revision'=>'minor','major_revision'=>'major','assign_reviewer'=>'review',default=>'proof'}))->format('Y-m-d') }}" required></label>@endif
@if(in_array($action,['save_copyediting','send_proof','proof_corrections']))@php $fileKey=match($action){'save_copyediting'=>'edited_manuscript','send_proof'=>'galley',default=>'correction'}; @endphp<label>{{ str($fileKey)->headline() }}<input class="portal-input" type="file" name="{{ $fileKey }}" accept="{{ $action==='send_proof'?'.pdf':'.pdf,.doc,.docx' }}" required></label>@endif
@if($action==='verify_metadata')
@foreach(['title','abstract','publication_type','volume','issue'] as $field)<label>{{ str($field)->headline() }}<textarea class="portal-textarea" rows="{{ $field==='abstract'?5:2 }}" name="{{ $field }}" required>{{ $article->$field }}</textarea></label>@endforeach
<label>Keywords (comma separated)<textarea class="portal-textarea" name="keywords" required>{{ implode(', ',$article->keywords??[]) }}</textarea></label><label>References (one per line)<textarea class="portal-textarea" name="references" required>{{ implode("\n",$article->references??[]) }}</textarea></label>
<label>Archive issue<select name="journal_issue_id" class="portal-select" required><option value="">Select existing archive issue</option>@foreach($issues as $issue)<option value="{{ $issue->id }}">{{ $issue->volume->year }} · Volume {{ $issue->volume->number }} · Issue {{ $issue->number }}</option>@endforeach</select></label>
<label>Year<input class="portal-input" name="year" type="number" value="{{ now()->year }}" required></label><label>Publication date<input class="portal-input" name="publication_date" type="date" required></label><label>Page numbers<input class="portal-input" name="pages" required></label><label>Final publication PDF<input class="portal-input" name="final_pdf" type="file" accept=".pdf" required></label><p>Verify the authors, affiliations and corresponding author listed in Overview.</p>
@endif
@if(in_array($action,['register_doi','activate_doi']))<label>DOI<input class="portal-input" name="doi" value="{{ $article->doi }}" placeholder="10.1234/example" required></label><label>DOI agency<input class="portal-input" name="agency" value="{{ data_get($data,'doi.agency') }}" required></label><label>Registration / resolution evidence URL<input class="portal-input" name="evidence_url" type="url" required></label><label class="check-row"><input type="checkbox" name="confirmed" value="1" required>I verified this {{ $action==='activate_doi'?'active DOI resolves to the correct article':'registration with the DOI agency' }}.</label><p>This records a manual verification; it does not register a DOI with an external agency.</p>@endif
@if($action==='save_indexing')<label>Indexing service<select class="portal-select" name="service_id" required>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select></label><label>Status<select class="portal-select" name="indexing_status">@foreach(['not_submitted','submitted','under_review','indexed','rejected'] as $s)<option value="{{ $s }}">{{ str($s)->headline() }}</option>@endforeach</select></label><label>Indexed record URL<input class="portal-input" name="indexed_url" type="url"></label>@endif
<label>Comments<textarea class="portal-textarea" name="comments" rows="3" @required(in_array($action,['return','reject','minor_revision','major_revision','accept','proof_corrections','pass_similarity','save_similarity']))></textarea></label>
