@extends('layouts.portal')
@section('title','Manuscript workflow') @section('section','Journal workflow') @section('page-title','Manuscripts')
@section('page-description','Submissions, editorial decisions, production and publication in one record.')
@section('page-actions')@if(auth()->user()->hasAnyRole('author','contributor'))<a class="portal-button primary" href="{{ route('author.articles.create') }}">Submit new manuscript</a>@endif @endsection
@section('content')
@if(auth()->user()->hasAnyRole('editor','admin','super-admin'))<p><a class="portal-button" href="{{ route('workflow.staff') }}">Editors & reviewers</a> @if(auth()->user()->hasRole('super-admin'))<a class="portal-button" href="{{ route('workflow.settings') }}">Workflow settings</a>@endif</p>@endif
<p><a class="portal-button" href="{{ route('workflow.index',array_merge(request()->except('page'),['export'=>'csv'])) }}">Download filtered report</a></p>
<div class="workflow-metrics">@foreach($counts as $stage=>$total)<a class="portal-card" href="{{ route('workflow.index',['stage'=>$stage]) }}"><small>{{ str($stage)->headline() }}</small><strong>{{ $total }}</strong></a>@endforeach</div>
<div class="portal-card"><div class="portal-card-body"><form method="get" class="workflow-filters">
@foreach(['q'=>'Title or manuscript ID','author'=>'Author','reviewer'=>'Reviewer ID','type'=>'Article type','date'=>'Submission date'] as $key=>$label)<label>{{ $label }}<input class="portal-input" name="{{ $key }}" value="{{ request($key) }}" type="{{ $key==='date'?'date':'text' }}"></label>@endforeach
<label>Current stage<select class="portal-select" name="stage"><option value="">All stages</option>@foreach(config('workflow.stages') as $stage)<option value="{{ $stage }}" @selected(request('stage')===$stage)>{{ str($stage)->headline() }}</option>@endforeach</select></label>
<label>Publication status<select class="portal-select" name="publication_status"><option value="">All</option>@foreach(\App\Enums\ArticleStatus::cases() as $s)<option value="{{ $s->value }}" @selected(request('publication_status')===$s->value)>{{ $s->label() }}</option>@endforeach</select></label><button class="portal-button primary">Filter</button><a class="portal-button" href="{{ route('workflow.index') }}">Reset</a></form></div>
<div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Manuscript ID / Title</th><th>Author / Editor</th><th>Submitted</th><th>Reviewers</th><th>Stage / Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>@forelse($articles as $article)<tr><td><strong>{{ $article->workflow?->manuscript_id??'Draft / existing record' }}</strong><br>{{ $article->title }}</td><td>{{ $article->creator?->name }}<br><small>{{ $article->assignedEditor?->name??'Editor unassigned' }}</small></td><td>{{ $article->submitted_at?->format('d M Y')??'—' }}</td><td>{{ $article->reviews->pluck('reviewer.name')->unique()->join(', ')?:'—' }}</td><td>{{ $article->workflow?->label()??$article->status->label() }}<br><x-portal.status :value="$article->status" /></td><td>{{ $article->updated_at->format('d M Y') }}</td><td><a class="portal-button" href="{{ route('workflow.show',$article) }}">View</a></td></tr>@empty<tr><td colspan="7">No manuscripts match these filters.</td></tr>@endforelse</tbody></table></div>{{ $articles->links() }}</div>
@if(auth()->user()->notifications()->exists())<div class="portal-card"><div class="portal-card-head"><h2>Notifications</h2></div><div class="portal-card-body">@foreach(auth()->user()->notifications()->latest()->limit(10)->get() as $notification)<p>{{ $notification->data['message']??$notification->data['title']??str($notification->data['type']??'Journal update')->headline() }} <small>{{ $notification->created_at->diffForHumans() }}</small></p>@endforeach</div></div>@endif
@endsection
