@extends('layouts.portal')
@section('title',$article->title) @section('section','Manuscript workflow') @section('page-title',$article->title)
@section('page-description',$article->workflow?->manuscript_id??'Complete your draft and submit it for editorial assessment.')
@section('page-actions')<a class="portal-button" href="{{ route('workflow.index') }}">All manuscripts</a>@if($article->created_by_id===auth()->id() && in_array($article->workflow?->stage??$article->status->value,['draft','returned','minor_revision','major_revision']))<a class="portal-button" href="{{ route('author.articles.edit',$article) }}">Edit manuscript details</a>@endif @endsection
@section('content')
@php $w=$article->workflow; $stage=$w?->stage??$article->status->value;$data=$w?->data??[]; $tab=request('tab','overview');$tabs=['overview'=>'Overview','files'=>'Files','reviews'=>'Reviews','revisions'=>'Revisions','proofs'=>'Proofs','publication'=>'Publication','activity'=>'Activity']; if($editor)$tabs+=['editorial'=>'Editorial','plagiarism'=>'Plagiarism','reviewers'=>'Reviewers','acceptance'=>'Acceptance','copyediting'=>'Copyediting','metadata'=>'Metadata','doi'=>'DOI','indexing'=>'Indexing']; @endphp
<div class="portal-card"><div class="portal-card-body"><div class="workflow-summary"><div><small>Current stage</small><h2>{{ str($stage)->headline() }}</h2></div><div><small>Editor</small><p>{{ $article->assignedEditor?->name??'Awaiting assignment' }}</p></div><div><small>Submission date</small><p>{{ $article->submitted_at?->format('d M Y')??'Not submitted' }}</p></div><div><small>Status</small><p>{{ $article->status->label() }}</p></div>@if($w?->deadline)<div><strong>{{ $w->deadline->isPast()?'OVERDUE':'Action due' }}</strong><p>{{ $w->deadline->format('d M Y') }} · {{ $w->deadline->diffForHumans() }}</p></div>@endif</div>
<ol class="workflow-tracker">@foreach(['submitted','initial_check','plagiarism_check','editorial_screening','reviewer_assignment','under_review','minor_revision','major_revision','revision_submitted','editor_recheck','reviewer_recheck','accepted','copyediting','proofing','final_proof_approved','metadata_verified','article_id_generated','doi_pending','ready_to_publish','published','indexing','archived'] as $step)@php $done=$activities->contains('from_stage',$step)&&$stage!==$step; @endphp<li @class(['is-current'=>$stage===$step,'is-complete'=>$done]) @if($stage===$step) aria-current="step" @endif>{{ $done?'✓ ':'' }}{{ str($step)->headline() }}</li>@endforeach</ol>
@if(in_array($stage,['returned','minor_revision','major_revision','proofing']))<div class="workflow-alert"><strong>ACTION REQUIRED — {{ $stage==='proofing'?'Proof ready for review':str($stage)->headline() }}</strong><p>{{ data_get($data,'revision_request.comments') }}</p></div>@endif
</div></div>
<nav class="workflow-tabs" aria-label="Manuscript sections">@foreach($tabs as $key=>$label)<a @class(['portal-button','primary'=>$tab===$key]) href="{{ route('workflow.show',[$article,'tab'=>$key]) }}">{{ $label }}</a>@endforeach</nav>
<div class="dashboard-grid" style="align-items:start"><div class="portal-form"><div class="portal-card"><div class="portal-card-head"><h2>{{ $tabs[$tab]??'Overview' }}</h2></div><div class="portal-card-body">
@if($tab==='overview')<h3>{{ $article->publication_type }}</h3><p style="white-space:pre-wrap">{{ $article->abstract }}</p><p><strong>Keywords:</strong> {{ implode(', ',$article->keywords??[]) }}</p><h3>Authors</h3>@foreach($article->authors as $author)<p><strong>{{ $author->name }}</strong> {{ $author->pivot->is_corresponding?'(Corresponding author)':'' }}<br>{{ $author->organization }} · {{ $author->department }} · {{ $author->country }}<br>{{ $author->email }} · {{ $author->orcid }}</p>@endforeach
@elseif(in_array($tab,['files','revisions','proofs','copyediting']))
@foreach($files as $file)@if($tab==='files'||($tab==='revisions'&&in_array($file->purpose,['manuscript','response','supplementary']))||($tab==='proofs'&&in_array($file->purpose,['galley','correction','final_pdf']))||($tab==='copyediting'&&$file->purpose==='edited_manuscript'))<div class="timeline-item"><strong>{{ str($file->purpose)->headline() }} · Version / round {{ $file->round }}</strong><p><a href="{{ route('workflow.download',$file) }}">{{ $file->original_name }}</a></p><small>{{ $file->uploader?->name }} · {{ $file->created_at->format('d M Y H:i') }}</small></div>@endif @endforeach
@if($files->isEmpty())<p>No files yet. Upload manuscript and cover letter when submitting.</p>@endif
@elseif(in_array($tab,['reviews','reviewers']))
@forelse($reviews as $review)<div class="timeline-item"><strong>{{ $review->reviewer?->name }} · {{ str($review->status->value)->headline() }}</strong><p>Deadline: {{ $review->due_at?->format('d M Y') }} {{ $review->due_at?->isPast() && $review->status->value!=='completed'?'— OVERDUE':'' }}</p>@if($review->recommendation)<p><strong>{{ str($review->recommendation->value)->headline() }}</strong></p><p style="white-space:pre-wrap">{{ $review->comments_to_author }}</p>@endif @if($editor)<details><summary>Confidential editor comments</summary><p>{{ $review->confidential_comments }}</p></details><p>{{ $review->response_note }}</p>@if($review->review_file_path)<p><a href="{{ route('workflow.review.file',$review) }}">Download confidential review attachment</a></p>@endif
@if($review->status->value==='completed'&&in_array($stage,['under_review','reviewer_recheck']))<form class="portal-form" method="post" action="{{ route('workflow.review.reopen',$review) }}">@csrf<label>Reopening reason<textarea class="portal-textarea" name="comments" required></textarea></label><label>New deadline<input class="portal-input" type="date" name="deadline" required></label><button class="portal-button">Reopen review</button></form>@endif @endif</div>@empty<p>No reviews yet.</p>@endforelse
@elseif($tab==='plagiarism')<p>Status: {{ str(data_get($data,'similarity.status','pending'))->headline() }}</p><p>Similarity: {{ data_get($data,'similarity.percentage','Pending') }}%</p><p>{{ data_get($data,'similarity.remarks') }}</p>@foreach($files->where('purpose','report') as $file)<p><a href="{{ route('workflow.download',$file) }}">{{ $file->original_name }}</a></p>@endforeach
@elseif(in_array($tab,['publication','metadata','doi','indexing','acceptance']))
@if(data_get($data,'acceptance'))<p><a class="portal-button" href="{{ route('workflow.acceptance',$article) }}">Download acceptance letter PDF</a></p>@endif
@if($tab==='doi'&&data_get($data,'doi.prepared_metadata'))<details><summary>Prepared deposit metadata</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{ json_encode(data_get($data,'doi.prepared_metadata'),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre></details>@endif
<dl class="detail-list"><div><dt>Article number</dt><dd>{{ $article->article_number??'Pending' }}</dd></div><div><dt>DOI</dt><dd>{{ $article->doi??'Pending' }}</dd></div><div><dt>Volume / Issue</dt><dd>{{ $article->volume??'—' }} / {{ $article->issue??'—' }}</dd></div><div><dt>Publication date</dt><dd>{{ data_get($data,'metadata.publication_date',$article->published_at?->format('Y-m-d'))??'Pending' }}</dd></div><div><dt>DOI status</dt><dd>{{ str(data_get($data,'doi.status','pending'))->headline() }}</dd></div></dl>
@if($article->status===\App\Enums\ArticleStatus::Published)<p><a class="portal-button" href="{{ route('articles.show',$article) }}">View published article</a></p>@endif
@foreach(data_get($data,'indexing',[]) as $id=>$record)<p>{{ $services->firstWhere('id',$id)?->name }} — {{ str($record['status'])->headline() }} @if($record['url']??null)<a href="{{ $record['url'] }}" rel="noopener" target="_blank">Indexed record</a>@endif</p>@endforeach
@else
<div class="timeline">@forelse($activities as $activity)<div class="timeline-item"><strong>{{ str($activity->action)->headline() }}</strong><p>{{ str($activity->from_stage)->headline() }} → {{ str($activity->to_stage)->headline() }}</p><p style="white-space:pre-wrap">{{ $activity->comments }}</p>@if($editor&&data_get($activity->data,'previous_report'))<details><summary>Previous review report</summary><p>{{ data_get($activity->data,'previous_report.comments_to_author') }}</p><p><strong>Confidential:</strong> {{ data_get($activity->data,'previous_report.confidential_comments') }}</p><p>{{ str(data_get($activity->data,'previous_report.recommendation'))->headline() }}</p></details>@endif<small>{{ $activity->actor?->name??'System' }} · {{ $activity->role }} · {{ $activity->created_at->format('d M Y H:i:s') }}</small></div>@empty<p>No activity yet.</p>@endforelse</div>
@endif
</div></div></div><aside class="portal-form">
<div class="portal-card"><div class="portal-card-head"><h2>Available actions</h2></div><div class="portal-card-body portal-form">
@forelse($actions as $action=>$definition)<details class="workflow-action" @if(count($actions)===1) open @endif><summary>{{ $definition['label'] }}</summary><form class="portal-form" method="post" enctype="multipart/form-data" action="{{ route('workflow.action',$article) }}" data-confirm="{{ $definition['label'] }}?">@csrf<input type="hidden" name="action" value="{{ $action }}">@include('workflow.action-fields')<button class="portal-button primary">{{ $definition['label'] }}</button></form></details>@empty<p>No action is required from you at this stage.</p>@endforelse
</div></div>
@if($editor&&$w)<details class="portal-card"><summary class="portal-card-head">Manage deadlines</summary><form class="portal-card-body portal-form" method="post" action="{{ route('workflow.deadline',$article) }}">@csrf<label>Deadline type<select class="portal-select" name="kind"><option value="manuscript">Author revision / proof</option><option value="review">Peer review</option><option value="invitation">Invitation acceptance</option></select></label><label>Review assignment<select class="portal-select" name="review_id"><option value="">Not applicable</option>@foreach($reviews as $r)<option value="{{ $r->id }}">{{ $r->reviewer?->name }} · {{ $r->status->value }}</option>@endforeach</select></label><input class="portal-input" name="deadline" type="date" required><textarea class="portal-textarea" name="comments" required placeholder="Reason for deadline change"></textarea><button class="portal-button">Update deadline</button></form></details>@endif
@if(auth()->user()->hasAnyRole('admin','super-admin'))<div class="portal-card"><div class="portal-card-body"><form class="portal-form" method="post" action="{{ route('workflow.assignment',$article) }}">@csrf<h3>Assign editor / ownership</h3><label>Editor<select class="portal-select" name="editor_id" required>@foreach($editors as $person)<option value="{{ $person->id }}" @selected($article->assigned_editor_id===$person->id)>{{ $person->name }}</option>@endforeach</select></label><label>New owner user ID (optional)<input class="portal-input" name="owner_id" type="number" min="1"></label><label>Reason<textarea class="portal-textarea" name="comments" required></textarea></label><button class="portal-button">Save assignment</button></form>
@if(!$w)<hr><form method="post" action="{{ route('workflow.adopt',$article) }}">@csrf<p>Adopt this existing record into the controlled workflow. Unpublished submissions restart at initial checks.</p><textarea class="portal-textarea" name="comments" required placeholder="Adoption reason"></textarea><button class="portal-button">Adopt existing record</button></form>@endif</div></div>@endif
@if(auth()->user()->hasRole('super-admin')&&$w)<details class="portal-card"><summary class="portal-card-head">Audited workflow correction</summary><form class="portal-card-body portal-form" method="post" action="{{ route('workflow.override',$article) }}">@csrf<p>Return a record for correction. Publication prerequisites remain enforced.</p><select class="portal-select" name="stage">@foreach(['submitted','initial_check','plagiarism_check','editorial_screening','reviewer_assignment','editor_recheck','copyediting'] as $s)<option value="{{ $s }}">{{ str($s)->headline() }}</option>@endforeach</select><textarea name="comments" class="portal-textarea" required minlength="20" placeholder="Detailed reason for override"></textarea><button class="portal-button danger">Record override</button></form></details>@endif
@include('admin.articles._homepage')
</aside></div>
@endsection
