<?php

return [
    'journal' => 'Singapore Journal of Cardiology', 'issn' => '27374025',
    'manuscript_format' => env('WORKFLOW_MANUSCRIPT_FORMAT', 'SJC-{year}-{sequence}'),
    'article_format' => env('WORKFLOW_ARTICLE_FORMAT', 'SJC-{year}-V{volume}-I{issue}-A{sequence}'),
    'deadlines' => ['invitation' => 7, 'review' => 21, 'minor' => 14, 'major' => 30, 'proof' => 7],
    'stages' => ['draft', 'submitted', 'initial_check', 'plagiarism_check', 'editorial_screening', 'reviewer_assignment', 'under_review', 'minor_revision', 'major_revision', 'revision_submitted', 'editor_recheck', 'reviewer_recheck', 'accepted', 'copyediting', 'proofing', 'author_corrections', 'final_proof_approved', 'metadata_verified', 'article_id_generated', 'doi_pending', 'doi_submitted', 'doi_registered', 'ready_to_publish', 'published', 'indexing', 'indexed', 'archived', 'returned', 'rejected'],
    'actions' => [
        'submit' => ['label' => 'Submit manuscript', 'from' => ['draft', 'returned'], 'to' => 'submitted', 'role' => 'author'],
        'start_check' => ['label' => 'Start initial check', 'from' => ['submitted'], 'to' => 'initial_check', 'role' => 'editor'],
        'approve_check' => ['label' => 'Approve format and documents', 'from' => ['initial_check'], 'to' => 'plagiarism_check', 'role' => 'editor'],
        'save_similarity' => ['label' => 'Record similarity assessment', 'from' => ['plagiarism_check'], 'to' => null, 'role' => 'editor'],
        'pass_similarity' => ['label' => 'Pass similarity check', 'from' => ['plagiarism_check'], 'to' => 'editorial_screening', 'role' => 'editor'],
        'send_review' => ['label' => 'Send for peer review', 'from' => ['editorial_screening'], 'to' => 'reviewer_assignment', 'role' => 'editor'],
        'return' => ['label' => 'Return to author', 'from' => ['initial_check', 'plagiarism_check', 'editorial_screening'], 'to' => 'returned', 'role' => 'editor'],
        'assign_reviewer' => ['label' => 'Send reviewer invitation', 'from' => ['reviewer_assignment', 'under_review', 'reviewer_recheck'], 'to' => null, 'role' => 'editor'],
        'minor_revision' => ['label' => 'Request minor revision', 'from' => ['under_review', 'revision_submitted', 'editor_recheck', 'reviewer_recheck'], 'to' => 'minor_revision', 'role' => 'editor'],
        'major_revision' => ['label' => 'Request major revision', 'from' => ['under_review', 'revision_submitted', 'editor_recheck', 'reviewer_recheck'], 'to' => 'major_revision', 'role' => 'editor'],
        'revise' => ['label' => 'Upload revised manuscript', 'from' => ['minor_revision', 'major_revision'], 'to' => 'revision_submitted', 'role' => 'author'],
        'editor_recheck' => ['label' => 'Begin editorial recheck', 'from' => ['revision_submitted'], 'to' => 'editor_recheck', 'role' => 'editor'],
        'reviewer_recheck' => ['label' => 'Send back to reviewers', 'from' => ['revision_submitted'], 'to' => 'reviewer_recheck', 'role' => 'editor'],
        'accept' => ['label' => 'Accept manuscript', 'from' => ['under_review', 'revision_submitted', 'editor_recheck', 'reviewer_recheck'], 'to' => 'accepted', 'role' => 'editor'],
        'reject' => ['label' => 'Reject manuscript', 'from' => ['initial_check', 'plagiarism_check', 'editorial_screening', 'reviewer_assignment', 'under_review', 'revision_submitted', 'editor_recheck', 'reviewer_recheck'], 'to' => 'rejected', 'role' => 'editor'],
        'start_copyediting' => ['label' => 'Start copyediting', 'from' => ['accepted'], 'to' => 'copyediting', 'role' => 'editor'],
        'save_copyediting' => ['label' => 'Save edited manuscript', 'from' => ['copyediting'], 'to' => null, 'role' => 'editor'],
        'send_proof' => ['label' => 'Send galley proof', 'from' => ['copyediting', 'author_corrections'], 'to' => 'proofing', 'role' => 'editor'],
        'proof_corrections' => ['label' => 'Submit proof corrections', 'from' => ['proofing'], 'to' => 'author_corrections', 'role' => 'author'],
        'approve_proof' => ['label' => 'Approve final proof', 'from' => ['proofing'], 'to' => 'final_proof_approved', 'role' => 'author'],
        'verify_metadata' => ['label' => 'Verify metadata', 'from' => ['final_proof_approved'], 'to' => 'metadata_verified', 'role' => 'editor'],
        'article_number' => ['label' => 'Generate article number', 'from' => ['metadata_verified'], 'to' => 'article_id_generated', 'role' => 'admin'],
        'prepare_doi' => ['label' => 'Prepare DOI metadata', 'from' => ['article_id_generated'], 'to' => 'doi_pending', 'role' => 'admin'],
        'submit_doi' => ['label' => 'Record DOI submission', 'from' => ['doi_pending'], 'to' => 'doi_submitted', 'role' => 'admin'],
        'register_doi' => ['label' => 'Record registered DOI', 'from' => ['doi_submitted'], 'to' => 'doi_registered', 'role' => 'admin'],
        'activate_doi' => ['label' => 'Confirm DOI active', 'from' => ['doi_registered'], 'to' => 'ready_to_publish', 'role' => 'admin'],
        'publish' => ['label' => 'Publish article', 'from' => ['ready_to_publish'], 'to' => 'published', 'role' => 'admin'],
        'indexing' => ['label' => 'Start indexing', 'from' => ['published'], 'to' => 'indexing', 'role' => 'admin'],
        'save_indexing' => ['label' => 'Record indexing result', 'from' => ['indexing', 'indexed'], 'to' => null, 'role' => 'admin'],
        'indexed' => ['label' => 'Mark indexing completed', 'from' => ['indexing'], 'to' => 'indexed', 'role' => 'admin'],
        'archive' => ['label' => 'Archive completed workflow', 'from' => ['indexed'], 'to' => 'archived', 'role' => 'admin'],
    ],
];
