@extends('layouts.portal')
@section('title','Manage articles') @section('section','Editorial') @section('eyebrow','Content inventory') @section('page-title','Articles') @section('page-description','Filter, edit, publish, schedule, feature, assign, archive, and restore journal content.')
@section('page-actions')<a class="portal-button primary" href="{{ route('admin.articles.create') }}"><x-portal.icon name="plus" :size="17" />New article</a>@endsection
@section('content')
<div class="portal-card"><form class="filter-bar" method="get"><div class="portal-field search-field"><label for="q">Search</label><input class="portal-input" id="q" name="q" value="{{ request('q') }}" placeholder="Title, author, topic…"></div><div class="portal-field"><label for="status">Status</label><select class="portal-select" id="status" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="portal-field"><label for="category">Category</label><select class="portal-select" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="portal-field"><label for="trashed">Archive</label><select class="portal-select" id="trashed" name="trashed"><option value="">Active</option><option value="only" @selected(request('trashed')==='only')>Trash only</option></select></div><button class="portal-button" type="submit"><x-portal.icon name="search" :size="17" />Filter</button></form>
@if($articles->isEmpty())<x-portal.empty title="No articles found" message="Try a different filter or create an editorial article." action="New article" :href="route('admin.articles.create')" />@else
<form id="bulk-form" method="post" action="{{ route('admin.articles.bulk') }}" data-confirm="Apply this bulk action to every selected article?" data-loading>@csrf<div class="filter-bar" style="border-top:1px solid var(--portal-line)"><div class="portal-field"><label for="bulk-action">Bulk action</label><select class="portal-select" id="bulk-action" name="action" required><option value="">Choose…</option><option value="publish">Publish eligible</option><option value="feature">Feature</option><option value="unfeature">Unfeature</option><option value="trend">Mark trending</option><option value="untrend">Remove trending</option><option value="delete">Move to trash</option><option value="category">Change category</option></select></div><div class="portal-field"><label for="bulk-category">Target category</label><select class="portal-select" id="bulk-category" name="category_id"><option value="">Choose category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><button class="portal-button" type="submit">Apply to selected</button></div></form>
<div class="portal-table-wrap"><table class="portal-table"><thead><tr><th><input type="checkbox" data-check-all="articles" aria-label="Select all"></th><th>Article</th><th>Status</th><th>Editor</th><th>Signals</th><th>Updated</th><th></th></tr></thead><tbody>@foreach($articles as $article)<tr><td>@unless($article->trashed())<input form="bulk-form" type="checkbox" name="article_ids[]" value="{{ $article->id }}" data-check-group="articles" aria-label="Select {{ $article->title }}">@endunless</td><td><a class="row-title" href="{{ $article->trashed() ? '#' : route('admin.articles.show',$article) }}">{{ $article->title }}</a><small>{{ $article->category?->name ?? 'Uncategorised' }} · {{ $article->creator?->name }}</small></td><td>@if($article->trashed())<span class="status-pill status-rejected"><i></i>Trashed</span>@else<x-portal.status :value="$article->status" />@endif</td><td>{{ $article->assignedEditor?->name ?? 'Unassigned' }}</td><td>{{ $article->is_featured ? 'Featured' : ($article->is_homepage_latest ? 'Latest hero' : '') }}{{ $article->is_featured && $article->is_trending ? ' · ' : '' }}{{ $article->is_trending ? 'Trending' : '' }}</td><td>{{ $article->updated_at->format('d M Y') }}</td><td>@if($article->trashed())<form method="post" action="{{ route('admin.articles.restore',$article->slug) }}">@csrf<button class="portal-button small" type="submit">Restore</button></form>@else<div class="row-actions"><a class="portal-button small" href="{{ route('admin.articles.show',$article) }}">Manage</a><a class="portal-button small" href="{{ route('admin.articles.edit',$article) }}">Edit</a></div>@endif</td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $articles->links() }}</div>@endif</div>
@endsection
