@extends('layouts.portal') @section('title',$article->title) @section('section','Editorial') @section('eyebrow','Workflow record') @section('page-title',$article->title) @section('page-description',$article->subtitle?:'Manage editorial state, assignments, signals, versions, and submission history.')
@section('page-actions')<a class="portal-button" href="{{ route('admin.articles.edit',$article) }}">Edit content</a>@if($article->status===\App\Enums\ArticleStatus::Published)<a class="portal-button primary" href="{{ route('articles.show',$article) }}">View live</a>@endif @endsection
@section('content')<p><a class="portal-button primary" href="{{ route('workflow.show',$article) }}">Open manuscript workflow</a></p>
<div class="dashboard-grid" style="align-items:start"><div class="portal-form"><div class="portal-card"><div class="portal-card-head"><div><h2>Publication record</h2><p>Updated {{ $article->updated_at->format('d M Y, H:i') }}</p></div><x-portal.status :value="$article->status" /></div><div class="portal-card-body"><dl class="detail-list"><div><dt>Creator</dt><dd>{{ $article->creator->name }}</dd></div><div><dt>Assigned editor</dt><dd>{{ $article->assignedEditor?->name??'Unassigned' }}</dd></div><div><dt>Authors</dt><dd>{{ $article->authors->pluck('name')->join(', ')?:'—' }}</dd></div><div><dt>Category</dt><dd>{{ $article->category?->name??'—' }}</dd></div><div><dt>Submitted</dt><dd>{{ $article->submitted_at?->format('d M Y, H:i')??'—' }}</dd></div><div><dt>Published / scheduled</dt><dd>{{ $article->published_at?->format('d M Y, H:i')??$article->scheduled_for?->format('d M Y, H:i')??'—' }}</dd></div><div><dt>Reader signals</dt><dd>{{ $article->is_featured?'Featured · ':'' }}{{ $article->is_trending?'Trending':'Standard' }}</dd></div><div><dt>Views</dt><dd>{{ number_format($article->view_count) }}</dd></div></dl></div></div>
<div class="portal-card"><div class="portal-card-head"><h2>Submission &amp; review history</h2></div><div class="portal-card-body"><div class="timeline">@forelse($article->submissions as $submission)<div class="timeline-item"><strong>Round {{ $submission->round }} · {{ str($submission->status->value)->headline() }}</strong><p>Version {{ $submission->version?->version_number??'—' }} · {{ $submission->reviews->count() }} reviewer(s)</p><small>{{ $submission->submitted_at->format('d M Y, H:i') }}</small></div>@empty<p class="portal-help">This article has not been submitted.</p>@endforelse</div></div></div>
<div class="portal-card"><div class="portal-card-head"><h2>Version history</h2></div><div class="portal-card-body"><div class="timeline">@foreach($article->versions as $version)<div class="timeline-item"><strong>Version {{ $version->version_number }}</strong><p>{{ $version->change_summary?:'Editorial snapshot' }}</p><small>{{ $version->created_at->format('d M Y, H:i') }} · {{ $version->creator?->name??'System' }}</small></div>@endforeach</div></div></div></div>
<aside class="portal-form"><div class="portal-card"><div class="portal-card-head"><h2>Editorial actions</h2></div><div class="portal-card-body portal-form">
@php $actions=match($article->status){\App\Enums\ArticleStatus::Submitted,\App\Enums\ArticleStatus::UnderReview=>['approve'=>'Accept','revision'=>'Request revision','reject'=>'Reject','withdraw'=>'Withdraw'],\App\Enums\ArticleStatus::Approved=>['production'=>'Send to production','publish'=>'Publish now','schedule'=>'Schedule'],\App\Enums\ArticleStatus::Production=>['publish'=>'Publish now','schedule'=>'Schedule'],\App\Enums\ArticleStatus::Scheduled=>['publish'=>'Publish now'],\App\Enums\ArticleStatus::Published=>['unpublish'=>'Unpublish'],\App\Enums\ArticleStatus::Archived=>['publish'=>'Republish'],default=>[]}; @endphp
@foreach($actions as $value=>$label)<form class="portal-form" method="post" action="{{ route('admin.articles.action',$article) }}" data-confirm="Confirm: {{ $label }}?">@csrf<input type="hidden" name="action" value="{{ $value }}">@if(in_array($value,['revision','reject']))<textarea class="portal-textarea" name="note" rows="3" placeholder="Decision rationale shared via workflow…" required></textarea>@endif @if($value==='schedule')<input class="portal-input" type="datetime-local" name="scheduled_for" min="{{ now()->addMinute()->format('Y-m-d\TH:i') }}" required>@endif<button @class(['portal-button','primary'=>$value==='publish'||$value==='approve','danger'=>$value==='reject']) type="submit">{{ $label }}</button></form>@endforeach
<hr style="border:0;border-top:1px solid var(--portal-line);width:100%"><form class="portal-form" method="post" action="{{ route('admin.articles.action',$article) }}">@csrf<input type="hidden" name="action" value="assign_editor"><div class="portal-field"><label for="editor">Assign editor</label><select class="portal-select" id="editor" name="user_id" required>@foreach($editors as $editor)<option value="{{ $editor->id }}" @selected($article->assigned_editor_id===$editor->id)>{{ $editor->name }}</option>@endforeach</select></div><button class="portal-button" type="submit">Assign editor</button></form>
@if(in_array($article->status,[\App\Enums\ArticleStatus::Submitted,\App\Enums\ArticleStatus::UnderReview],true))<form class="portal-form" method="post" action="{{ route('admin.articles.action',$article) }}">@csrf<input type="hidden" name="action" value="assign_reviewer"><div class="portal-field"><label for="reviewer">Assign reviewer</label><select class="portal-select" id="reviewer" name="user_id" required>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->id }}">{{ $reviewer->name }}</option>@endforeach</select></div><div class="portal-field"><label for="due_at">Review deadline</label><input class="portal-input" id="due_at" type="date" name="due_at" min="{{ now()->addDay()->format('Y-m-d') }}"></div><button class="portal-button" type="submit">Assign reviewer</button></form>@endif
</div></div>@include('admin.articles._homepage')
@can('delete',$article)<form method="post" action="{{ route('admin.articles.destroy',$article) }}" data-confirm="Move this article to trash?">@csrf @method('delete')<button class="portal-button danger" type="submit">Move to trash</button></form>@endcan</aside></div>
@endsection
