@extends('layouts.portal')
@php $version=$review->submission?->version; $locked=$review->status===\App\Enums\ReviewStatus::Completed; $awaitingResponse=$review->status===\App\Enums\ReviewStatus::Assigned; @endphp
@section('title','Review: '.$review->article->title) @section('section','Peer review') @section('eyebrow','Review assignment') @section('page-title',$review->article->title)
@section('page-description','Round '.($review->submission?->round ?? '—').' · Assigned '.($review->created_at->format('d M Y')).($review->due_at ? ' · Due '.$review->due_at->format('d M Y') : '').($review->article->trashed() ? ' · Archived manuscript' : ''))
@section('page-actions')@if($review->article->pdf_path)<a class="portal-button" href="{{ route('reviewer.reviews.manuscript',$review) }}"><x-portal.icon name="download" :size="17" />Download manuscript</a>@endif<a class="portal-button" href="{{ route('reviewer.dashboard') }}">Back to assignments</a>@endsection
@section('content')
<div class="dashboard-grid" style="grid-template-columns:minmax(0,1.35fr) minmax(340px,.8fr);align-items:start"><div class="portal-form"><div class="portal-card"><div class="portal-card-head"><div><h2>{{ $version?->title ?? $review->article->title }}</h2><p>Immutable submission snapshot · Version {{ $version?->version_number ?? 'current' }}</p></div><x-portal.status :value="$review->status" /></div><div class="portal-card-body"><dl class="detail-list"><div><dt>Category</dt><dd>{{ $review->article->category?->name ?? '—' }}</dd></div><div><dt>Authors</dt><dd>{{ $review->article->authors->pluck('name')->join(', ') ?: 'Anonymous' }}</dd></div><div><dt>Keywords</dt><dd>{{ implode(', ',$version?->keywords ?? $review->article->keywords ?? []) ?: '—' }}</dd></div><div><dt>Type</dt><dd>{{ str($review->article->publication_type)->headline() }}</dd></div></dl></div></div>
<div class="portal-card"><div class="portal-card-head"><h2>Abstract</h2></div><div class="portal-card-body prose-panel">{{ $version?->abstract ?? $review->article->abstract ?: 'No abstract supplied.' }}</div></div>
<div class="portal-card"><div class="portal-card-head"><h2>Manuscript</h2></div><div class="portal-card-body prose-panel">{!! $version?->content ?? $review->article->content !!}</div></div>
@if(filled($version?->references ?? $review->article->references))<div class="portal-card"><div class="portal-card-head"><h2>References</h2></div><div class="portal-card-body"><ol class="prose-panel">@foreach(($version?->references ?? $review->article->references) as $reference)<li>{{ $reference }}</li>@endforeach</ol></div></div>@endif
</div><aside class="portal-card"><div class="portal-card-head"><div><h2>{{ $locked ? 'Submitted report' : 'Your review' }}</h2><p>{{ $locked ? 'This report is immutable.' : 'Be specific, constructive, and evidence-led.' }}</p></div></div><div class="portal-card-body">
@if($locked)<dl class="detail-list" style="grid-template-columns:1fr"><div><dt>Recommendation</dt><dd><x-portal.status :value="$review->recommendation" /></dd></div><div><dt>Comments to author</dt><dd style="white-space:pre-wrap;line-height:1.6">{{ $review->comments_to_author }}</dd></div><div><dt>Confidential comments to editors</dt><dd style="white-space:pre-wrap;line-height:1.6">{{ $review->confidential_comments ?: 'None' }}</dd></div><div><dt>Submitted</dt><dd>{{ $review->completed_at->format('d M Y, H:i') }}</dd></div></dl>
@elseif($awaitingResponse)<div class="portal-form"><p>Please accept the assignment after checking for conflicts, or decline it with a confidential reason.</p><form method="post" action="{{ route('reviewer.reviews.accept',$review) }}">@csrf<button class="portal-button primary" type="submit">Accept assignment</button></form><form class="portal-form" method="post" action="{{ route('reviewer.reviews.decline',$review) }}">@csrf<div class="portal-field"><label for="response_note">Reason for declining</label><textarea class="portal-textarea" id="response_note" name="response_note" required maxlength="2000"></textarea></div><label class="check-row"><input type="checkbox" name="conflict_declared" value="1"><span>I am declining because of a conflict of interest</span></label><button class="portal-button" type="submit">Decline assignment</button></form></div>
@else<form class="portal-form" method="post" enctype="multipart/form-data" action="{{ route('reviewer.reviews.update',$review) }}" data-confirm="Submit and lock this review? You will not be able to edit it afterward." data-loading>@csrf @method('put')
    <div class="portal-field"><label for="recommendation">Recommendation</label><select class="portal-select" id="recommendation" name="recommendation" required><option value="">Choose one</option>@foreach(\App\Enums\ReviewRecommendation::cases() as $recommendation)<option value="{{ $recommendation->value }}" @selected(old('recommendation')===$recommendation->value)>{{ str($recommendation->value)->replace('_',' ')->headline() }}</option>@endforeach</select><x-portal.field-error name="recommendation" /></div>
    <div class="portal-field"><label for="comments_to_author">Comments to author</label><textarea class="portal-textarea" id="comments_to_author" name="comments_to_author" rows="12" required minlength="40">{{ old('comments_to_author') }}</textarea><p class="portal-help">Shared verbatim with the author.</p><x-portal.field-error name="comments_to_author" /></div>
    <div id="inline-comments"></div><template id="review-comment-template"><div class="portal-card-body" style="border:1px solid var(--portal-line);border-radius:8px;margin-bottom:.6rem"><div class="portal-field"><label>Location</label><input class="portal-input" name="comments[__INDEX__][location]" placeholder="Page, section, paragraph…"></div><div class="portal-field"><label>Comment</label><textarea class="portal-textarea" name="comments[__INDEX__][body]" rows="3" required></textarea></div></div></template>
    <button class="portal-button" type="button" data-add-review-comment="#inline-comments" data-template="#review-comment-template"><x-portal.icon name="plus" :size="17" />Add location-specific comment</button>
    <div class="portal-field"><label for="confidential_comments">Confidential comments to editors <span>optional</span></label><textarea class="portal-textarea" id="confidential_comments" name="confidential_comments" rows="6">{{ old('confidential_comments') }}</textarea><p class="portal-help">Never shown to the author.</p></div>
    <div class="portal-field"><label for="review_file">Review file <span>optional</span></label><input class="portal-input" id="review_file" name="review_file" type="file" accept=".pdf,.doc,.docx,.odt"><p class="portal-help">Private attachment for the editorial team.</p></div>
    <div class="check-row"><input id="confirmation" name="confirmation" type="checkbox" value="1" required><label for="confirmation">I have completed an independent review and understand this report is locked on submission.</label></div><x-portal.field-error name="confirmation" />
    <button class="portal-button primary" type="submit" data-loading-text="Submitting review…">Submit final review</button>
</form>@endif</div></aside></div>
@endsection
