@extends('layouts.portal')
@section('title', 'Author dashboard') @section('section', 'Author studio') @section('eyebrow', 'Your publishing practice')
@section('page-title', 'Good to see you, '.str(auth()->user()->name)->before(' '))
@section('page-description', 'Keep manuscripts moving from first draft to publication, with every revision safely recorded.')
@section('page-actions')<a class="portal-button primary" href="{{ route('author.articles.create') }}"><x-portal.icon name="plus" :size="17" />New manuscript</a>@endsection
@section('content')
<div class="metric-grid"><x-portal.metric label="All manuscripts" :value="$stats['total']" hint="Across every stage"/><x-portal.metric label="Working drafts" :value="$stats['draft']" tone="gold" hint="Private to you"/><x-portal.metric label="Under review" :value="$stats['under_review'] + $stats['submitted']" tone="blue" hint="With the editorial team"/><x-portal.metric label="Published" :value="$stats['published']" hint="Live in the journal"/></div>
@if($stats['revision_required'])<div class="portal-card" style="border-left:4px solid var(--portal-gold);margin-bottom:1rem"><div class="portal-card-body" style="display:flex;gap:1rem;justify-content:space-between;align-items:center"><div><strong>{{ $stats['revision_required'] }} manuscript(s) need revision</strong><p class="portal-help">Review the feedback, update your work, then resubmit a new version.</p></div><a class="portal-button" href="{{ route('author.articles.index',['status'=>'revision_required']) }}">Review feedback</a></div></div>@endif
<div class="portal-card"><div class="portal-card-head"><div><h2>Recent manuscripts</h2><p>Your most recently edited work</p></div><a class="portal-button small" href="{{ route('author.articles.index') }}">View all</a></div>
@if($recentArticles->isEmpty())<x-portal.empty title="Begin your first manuscript" message="Drafts autosave while you write, and stay private until you submit." action="New manuscript" :href="route('author.articles.create')" />@else
<div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Manuscript</th><th>Discipline</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>@foreach($recentArticles as $article)<tr><td><a class="row-title" href="{{ route('author.articles.show',$article) }}">{{ $article->title }}</a><small>{{ $article->subtitle ?: 'No subtitle' }}</small></td><td>{{ $article->category?->name ?? 'Uncategorised' }}</td><td><x-portal.status :value="$article->status" /></td><td>{{ $article->updated_at->diffForHumans() }}</td><td><a class="portal-button small" href="{{ route('author.articles.show',$article) }}">Open</a></td></tr>@endforeach</tbody></table></div>@endif</div>
@endsection
