@extends('layouts.portal')
@section('title','Assign a reviewer')
@section('section','Peer review')
@section('page-title','Assign a reviewer')
@section('page-description',$article->title)
@section('page-actions')<a class="portal-button" href="{{ route('admin.assign-reviewer.index') }}">← Choose another manuscript</a>@endsection
@section('content')
@if(!$ready)
<div class="portal-card"><div class="portal-card-head"><h2>Complete editorial checks first</h2></div><div class="portal-card-body"><p>Current stage: <strong>{{ str($article->workflow?->stage ?? $article->status->value)->headline() }}</strong>.</p><p>Review invitations become available after the initial check, similarity assessment, and editorial screening. Open the manuscript and complete its next available action.</p><a class="portal-button primary" href="{{ route('workflow.show',$article) }}">Continue editorial checks →</a></div></div>
@else
<form class="portal-form" method="post" action="{{ route('admin.assign-reviewer.store',$article) }}" data-loading>@csrf
<div class="portal-card"><div class="portal-card-head"><div><h2>2. Choose an available reviewer</h2><p>Authors, unavailable reviewers, and reviewers already assigned in this round are excluded.</p></div></div><div class="portal-card-body portal-form">
@forelse($reviewers as $reviewer)<label class="portal-card"><span class="portal-card-body" style="display:flex;gap:14px;align-items:flex-start"><input type="radio" name="reviewer_id" value="{{ $reviewer->id }}" @checked((string)old('reviewer_id')===(string)$reviewer->id) required><span><strong>{{ $reviewer->name }}</strong><br>{{ $reviewer->organization ?: 'Institution not provided' }}<br><small>{{ data_get($reviewer->reviewer_profile,'expertise') ?: 'Expertise not provided' }} · {{ $reviewer->active_reviews_count }} active reviews</small></span></span></label>
@empty<p>No eligible reviewers are available. An administrator can approve a reviewer account under People &amp; roles, or an existing reviewer can update their availability.</p>@endforelse<x-portal.field-error name="reviewer_id" /></div></div>
@if($reviewers->isNotEmpty())<div class="portal-card"><div class="portal-card-head"><h2>3. Set dates and send</h2></div><div class="portal-card-body portal-form"><div class="form-grid"><div class="portal-field"><label for="invitation_deadline">Reply to invitation by</label><input class="portal-input" id="invitation_deadline" type="date" name="invitation_deadline" value="{{ old('invitation_deadline',now()->addDays(7)->toDateString()) }}" min="{{ now()->addDay()->toDateString() }}" required><x-portal.field-error name="invitation_deadline" /></div><div class="portal-field"><label for="deadline">Submit review by</label><input class="portal-input" id="deadline" type="date" name="deadline" value="{{ old('deadline',now()->addDays(21)->toDateString()) }}" min="{{ now()->addDay()->toDateString() }}" required><x-portal.field-error name="deadline" /></div></div><div class="portal-field"><label for="editor_message">Message to reviewer</label><textarea class="portal-textarea" id="editor_message" name="editor_message" rows="4" required>{{ old('editor_message','Please review this manuscript within your area of expertise. Accept or decline the invitation after checking for conflicts of interest.') }}</textarea><x-portal.field-error name="editor_message" /></div><p>The reviewer can accept or decline before preparing their report.</p><button class="portal-button primary" type="submit" data-loading-text="Sending invitation…">Send review invitation</button></div></div>@endif
</form>
@endif
<div class="portal-card" style="margin-top:24px"><div class="portal-card-head"><h2>Assignment history</h2></div><div class="portal-card-body">@forelse($article->reviews as $review)<p><strong>{{ $review->reviewer?->name ?? 'Reviewer unavailable' }}</strong> · {{ str($review->status->value)->headline() }} · Due {{ $review->due_at?->format('d M Y') ?? 'Not set' }} <a href="{{ route('admin.reviews.show',$review) }}">View details</a></p>@empty<p>No invitations have been sent for this manuscript.</p>@endforelse</div></div>
@endsection
