@extends('layouts.portal')
@section('title', str($resource)->headline())
@section('section', 'Website')
@section('eyebrow', 'Content management')
@section('page-title', str($resource)->headline())
@section('page-description', 'Edit the information shown on your website.')
@section('content')
@php
    $fields = match($resource) {
        'authors' => ['name','designation','organization','affiliation','country','biography'],
        'volumes' => ['number','year','title'], 'issues' => ['journal_volume_id','number','title','description','cover','publication_date'],
        'editorial-members' => ['name','group','role','institution','department','country','credentials','orcid','biography','sort_order','photo'],
        'indexing-services' => ['name','description','official_url','status','sort_order','logo'], default => ['key','audience','subject','body'],
    };
    $required = ['number','year','name','group','role','status','key','audience','subject','journal_volume_id'];
    $choices = ['group'=>['editorial_board'=>'Editorial Board','reviewers'=>'Reviewers','advisors'=>'Advisors','publisher_staff'=>'Publisher / Administrative Staff'],'status'=>['pending_verification'=>'Pending verification','verified'=>'Verified','not_indexed'=>'Not indexed'],'audience'=>['author'=>'Author','reviewer'=>'Reviewer','editor_admin'=>'Editor / Admin']];
@endphp
@if($resource==='authors')<form method="get" class="portal-filters"><label for="author-search">Find an author</label><input class="portal-input" id="author-search" name="q" value="{{ request('q') }}" placeholder="Author name"><button class="portal-button" type="submit">Search</button></form>@endif
<div class="portal-form">
<section class="portal-card"><div class="portal-card-head"><h2>Add {{ str($resource)->singular()->headline() }}</h2></div><div class="portal-card-body"><form class="portal-form" method="post" enctype="multipart/form-data" action="{{ route('admin.readiness.store',$resource) }}">@csrf <div class="form-grid">@foreach($fields as $field)<div @class(['portal-field', 'field-span'=>in_array($field,['biography','description','body'])])><label for="new-{{ $field }}">{{ str($field)->headline() }}</label>@include('admin.readiness.field',['record'=>null,'field'=>$field])</div>@endforeach</div><label class="check-row"><input type="checkbox" name="is_active" value="1" checked><span>Publish / make active</span></label>@if(in_array($resource,['volumes','issues']))<label class="check-row"><input type="checkbox" name="is_current" value="1"><span>Current publication record</span></label>@endif<button class="portal-button primary" type="submit">Add record</button></form></div></section>
<section class="portal-card"><div class="portal-card-head"><h2>Existing records</h2><p>{{ $records->total() }} total</p></div><div class="portal-card-body"><div class="portal-form">@forelse($records as $record)<details class="portal-card"><summary style="cursor:pointer;padding:1rem 1.2rem"><strong>{{ $record->name ?? $record->title ?? $record->number ?? $record->key }}</strong><small style="margin-left:.5rem">{{ $record->role ?? $record->status ?? $record->year ?? $record->publication_date }}</small></summary><div class="portal-card-body"><form class="portal-form" method="post" enctype="multipart/form-data" action="{{ route('admin.readiness.update',[$resource,$record->id]) }}">@csrf @method('put')<div class="form-grid">@foreach($fields as $field)<div @class(['portal-field', 'field-span'=>in_array($field,['biography','description','body'])])><label for="{{ $record->id }}-{{ $field }}">{{ str($field)->headline() }}</label>@include('admin.readiness.field',['record'=>$record,'field'=>$field])</div>@endforeach</div><label class="check-row"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($record->is_active)><span>Published / active</span></label>@if(in_array($resource,['volumes','issues']))<label class="check-row"><input type="hidden" name="is_current" value="0"><input type="checkbox" name="is_current" value="1" @checked($record->is_current)><span>Current publication record</span></label>@endif<div class="form-actions"><button class="portal-button primary">Save changes</button></div></form><form method="post" action="{{ route('admin.readiness.destroy',[$resource,$record->id]) }}" data-confirm="Remove this record?">@csrf @method('delete')<button class="portal-button danger">Delete record</button></form></div></details>@empty<x-portal.empty title="No records yet" message="Add a record to get started." />@endforelse</div>{{ $records->links() }}</div></section></div>
@endsection
